# Generated by Django 6.0.1 on 2026-02-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
