# Generated by Django 6.0.1 on 2026-02-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
