# Generated by Django 6.0.1 on 2026-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_uploadedfile_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
